### ISSUE TITLE
Error: Invalid Configuration

### ISSUE THREAD

**Issue by jfornoff** [GLab/ToMaTo#1158] opened 2016-01-19 10:13 UTC
Hi,

there is what seems to be a regression on master.tomato-lab.org.
It occurs upon opening existing topologies in the web frontend, and creating new topology via API as well as via web frontend.

Error displayed by web frontend after clicking "Create new topology"
![tomato_invalidconf](https://cloud.githubusercontent.com/assets/1319818/12415673/49ab570c-be9d-11e5-949e-43fa7e79df13.jpg)

Stacktrace when trying to create a new topology (upon adding first host)
![tomato_stacktrace](https://cloud.githubusercontent.com/assets/1319818/12415735/8b7864ea-be9d-11e5-9eef-7d06d5b66afc.jpg)

Let me know if I can provide you with any more info.
Thanks,
Jan

**Comment by dswd** [comment] 2016-01-19 10:59
Hi Jan,

that behavior was caused by a deadlock in ToMaTo which has been addressed in #1156.
It should be working right now.

Dennis

**Closed by dswd** 2016-01-19 10:59 UTC

**Comment by jfornoff** [comment] 2016-01-19 11:36
Looks good, thanks!
